version: '3.8'

volumes:
  kafka_db:
    driver: local


services:
  kafka:
    build: .
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_db:/bitnami/kafka
    environment:
     - KAFKA_OPTS=-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf
     - KAFKA_CFG_NODE_ID=1
     - KAFKA_CFG_PROCESS_ROLES=broker,controller
     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
     - ALLOW_PLAINTEXT_LISTENER=yes
     - ALLOW_PLAINTEXT_LISTENER=yes